# Etapa de build (usamos Node para compilar Vite)
FROM node:18 AS builder

WORKDIR /app

# Instala solo dependencias necesarias
COPY package*.json ./
RUN npm install

# Copiamos el código y construimos la app
COPY . .
RUN npm run build

# Etapa final: Nginx para servir contenido estático
FROM nginx:stable-alpine

# Copiamos el build al directorio público
COPY --from=builder /app/dist /usr/share/nginx/html

# Reemplazamos la configuración por la nuestra
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
